### ISSUE TITLE
`fs-storage`: Port `BaseStorage` abstraction from Kotlin

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ark-rust#18]
Port functionality from [BaseStorage.kt](https://github.com/ARK-Builders/arklib-android/blob/main/lib/src/main/java/dev/arkbuilders/arklib/data/storage/BaseStorage.kt) into `fs-storage`.

It seems to me, that it should be a `trait `.

**Comment by twitu** [comment]
https://github.com/ARK-Builders/arklib-android/blob/main/lib/src/main/java/dev/arkbuilders/arklib/data/storage/Monoid.kt#L3

The kotlin monoid implementation is functionally equivalent to what modern CRDT libraries are offering. While we can go for a custom implementation it is error prone and require extra dev effort for implementing and maintaining. I can look into existing CRDT rust implementations for a feature set that suits us.

**Comment by twitu** [comment]
The Kotline BaseStorage implementation has the file storage logic and a few other things -
1. Stores the state of the key value pair mapping
2. Combining and returning mapping values using monoids
3. Mutex to gain exclusively access to mapping
4. CoroutineScope for asynchrony

I believe 3 and 4 require interfacing with many others parts and will be best handled separately. Here are a few comments on 1 and 2.

For 1, Rust traits can only store constants, they can't store dynamic data. So the trait can be something like this.

```rust
trait Storage {
    let valueById: HashMap<K, V>... // doesn't work
    fn getValueById(&self) -> HashMap<K, V> // works
}
```

This means that the structs must store the HashMap instead of returning them. This makes sense to me as the FileStorage will encapsulate the state of the underlying file.

However, BaseStorage also uses monoids to return values for keys that don't exist. Is this the behaviour, we want to expose to the user? Most Rust libraries, I've seen, prefer return a Result or an Option and letting the user decide what do with it. I think returning a neutral value can make it hard for users to figure out the failure cases.

```Kotlin
    override fun getValue(id: ResourceId) =
        valueById[id] ?: monoid.neutral
```

**Comment by kirillt** [comment]
@twitu That's a good point about `Result`. I think, we could use it at least for the initial implementation.

The main idea behind `BaseStorage` is simply share common code between `FileStorage` and `FolderStorage`. So we could start with implementing `FolderStorage` and create `BaseStorage` as utility abstraction.

Mutex and asynchronous things doesn't look necessary at this moment. Monoids are in separate issue.

> For 1, Rust traits can only store constants, they can't store dynamic data.

Indeed, we don't use OOP-style abstractions in Rust... I see 2 possible approaches here:
1. Use trait functions to expose map-like API which is implemented by structs.
2. Use aggregation, so `BaseStorage` would be inner structure holding the map and implementing common functions.
